;;; codex-ide-delete-session-thread-tests.el --- Tests for delete-session-thread -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused ERT coverage for thread deletion.

;;; Code:

(require 'ert)
(require 'codex-ide-test-fixtures)
(require 'codex-ide)

(ert-deftest codex-ide-delete-session-thread-deletes-live-session-via-app-server ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (deleted-session nil)
        (deleted-session-skip-unsubscribe nil)
        (requests nil)
        (prompt nil))
    (codex-ide-test-with-fixture project-dir
				 (codex-ide-test-with-fake-processes
				  (let ((session (codex-ide--create-process-session)))
				    (setf (codex-ide-session-thread-id session) "thread-delete-1")
				    (cl-letf (((symbol-function 'codex-ide--thread-rollout-path)
					       (lambda (&rest _)
						 (ert-fail "thread/delete should not inspect rollout storage")))
					      ((symbol-function 'codex-ide--request-sync)
					       (lambda (request-session method params)
						 (push (list request-session method params) requests)
						 '((ok . t))))
					      ((symbol-function 'yes-or-no-p)
					       (lambda (message)
						 (setq prompt message)
						 t))
					      ((symbol-function 'codex-ide--delete-live-thread-session)
					       (lambda (value &optional skip-unsubscribe)
						 (setq deleted-session value
						       deleted-session-skip-unsubscribe skip-unsubscribe)))
					      ((symbol-function 'codex-ide--delete-thread-storage)
					       (lambda (&rest _)
						 (ert-fail "thread/delete should avoid direct storage deletion"))))
				      (codex-ide-delete-session-thread "thread-delete-1")
				      (should (eq deleted-session session))
				      (should deleted-session-skip-unsubscribe)
				      (should (equal (mapcar #'cadr (nreverse requests))
						     '("thread/delete")))
				      (should (eq (caar requests) session))
				      (should (equal (caddar requests)
						     '((threadId . "thread-delete-1"))))
				      (should (string-match-p
					       (regexp-quote
						(buffer-name (codex-ide-session-buffer session)))
					       prompt))))))))

(ert-deftest codex-ide-delete-session-thread-deletes-stored-thread-via-query-session ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (query-session nil)
        (request-session nil)
        (request-method nil)
        (request-params nil))
    (codex-ide-test-with-fixture project-dir
				 (codex-ide-test-with-fake-processes
				  (setq query-session (codex-ide--create-query-session))
				  (cl-letf (((symbol-function 'codex-ide--ensure-query-session-for-thread-selection)
					     (lambda (&optional directory)
					       (should (equal directory
							      (file-name-as-directory project-dir)))
					       query-session))
					    ((symbol-function 'codex-ide--thread-rollout-path)
					     (lambda (&rest _)
					       (ert-fail "thread/delete should not inspect rollout storage")))
					    ((symbol-function 'codex-ide--request-sync)
					     (lambda (session method params)
					       (setq request-session session
						     request-method method
						     request-params params)
					       '((ok . t))))
					    ((symbol-function 'codex-ide--delete-thread-storage)
					     (lambda (&rest _)
					       (ert-fail "thread/delete should avoid direct storage deletion"))))
				    (codex-ide-delete-session-thread "thread-delete-stored" t)
				    (should (eq request-session query-session))
				    (should (equal request-method "thread/delete"))
				    (should (equal request-params
						   '((threadId . "thread-delete-stored")))))))))

(ert-deftest codex-ide-delete-session-thread-falls-back-when-app-server-delete-is-unsupported ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (deleted-session nil)
        (deleted-session-skip-unsubscribe :unset)
        (deleted-storage nil))
    (codex-ide-test-with-fixture project-dir
				 (codex-ide-test-with-fake-processes
				  (let ((session (codex-ide--create-process-session)))
				    (setf (codex-ide-session-thread-id session) "thread-delete-old")
				    (cl-letf (((symbol-function 'codex-ide--request-sync)
					       (lambda (_session method _params)
						 (should (equal method "thread/delete"))
						 (error "Codex app-server request thread/delete failed: Invalid request: unknown variant `thread/delete`, expected `thread/subscribe`")))
					      ((symbol-function 'codex-ide--thread-rollout-path)
					       (lambda (_thread-id)
						 "/tmp/codex-thread-delete-old.jsonl"))
					      ((symbol-function 'codex-ide--delete-live-thread-session)
					       (lambda (value &optional skip-unsubscribe)
						 (setq deleted-session value
						       deleted-session-skip-unsubscribe skip-unsubscribe)))
					      ((symbol-function 'codex-ide--delete-thread-storage)
					       (lambda (rollout-path)
						 (setq deleted-storage rollout-path))))
				      (codex-ide-delete-session-thread "thread-delete-old" t)
				      (should (eq deleted-session session))
				      (should-not deleted-session-skip-unsubscribe)
				      (should (equal deleted-storage
						     "/tmp/codex-thread-delete-old.jsonl"))))))))

(ert-deftest codex-ide-delete-session-thread-cancel-keeps-live-session-and-storage ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (deleted-session nil)
        (deleted-storage nil)
        (request nil))
    (codex-ide-test-with-fixture project-dir
				 (codex-ide-test-with-fake-processes
				  (let ((session (codex-ide--create-process-session)))
				    (setf (codex-ide-session-thread-id session) "thread-delete-2")
				    (cl-letf (((symbol-function 'codex-ide--thread-rollout-path)
					       (lambda (&rest _)
						 "/tmp/codex-thread-delete-2.jsonl"))
					      ((symbol-function 'codex-ide--request-sync)
					       (lambda (&rest args)
						 (setq request args)))
					      ((symbol-function 'yes-or-no-p)
					       (lambda (&rest _) nil))
					      ((symbol-function 'codex-ide--delete-live-thread-session)
					       (lambda (value &optional _skip-unsubscribe)
						 (setq deleted-session value)))
					      ((symbol-function 'codex-ide--delete-thread-storage)
					       (lambda (&rest args)
						 (setq deleted-storage args))))
				      (should-error (codex-ide-delete-session-thread "thread-delete-2")
						    :type 'user-error)
				      (should-not request)
				      (should-not deleted-session)
				      (should-not deleted-storage)
				      (should (buffer-live-p (codex-ide-session-buffer session)))))))))

(ert-deftest codex-ide-delete-session-thread-errors-when-fallback-storage-is-missing ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (deleted-storage nil))
    (codex-ide-test-with-fixture project-dir
				 (codex-ide-test-with-fake-processes
				  (let ((query-session (codex-ide--create-query-session)))
				    (cl-letf (((symbol-function 'codex-ide--ensure-query-session-for-thread-selection)
					       (lambda (&rest _) query-session))
					      ((symbol-function 'codex-ide--request-sync)
					       (lambda (_session method _params)
						 (should (equal method "thread/delete"))
						 (error "Codex app-server request thread/delete failed: Unknown method")))
					      ((symbol-function 'codex-ide--thread-rollout-path)
					       (lambda (&rest _) nil))
					      ((symbol-function 'codex-ide--delete-thread-storage)
					       (lambda (&rest args)
						 (setq deleted-storage args))))
					    (should-error (codex-ide-delete-session-thread "thread-delete-missing" t)
							  :type 'user-error)
					    (should-not deleted-storage)))))))

(ert-deftest codex-ide-delete-session-thread-does-not-fallback-for-delete-failures ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (deleted-session nil)
        (deleted-storage nil))
    (codex-ide-test-with-fixture project-dir
      (codex-ide-test-with-fake-processes
        (let ((session (codex-ide--create-process-session)))
          (setf (codex-ide-session-thread-id session) "thread-delete-fail")
          (cl-letf (((symbol-function 'codex-ide--request-sync)
                     (lambda (_session method _params)
                       (should (equal method "thread/delete"))
                       (error "Codex app-server request thread/delete failed: no rollout found for thread id thread-delete-fail (code -32600)")))
                    ((symbol-function 'codex-ide--thread-rollout-path)
                     (lambda (&rest _)
                       (ert-fail "non-unsupported delete failures should not inspect rollout storage")))
                    ((symbol-function 'codex-ide--delete-live-thread-session)
                     (lambda (value &optional _skip-unsubscribe)
                       (setq deleted-session value)))
                    ((symbol-function 'codex-ide--delete-thread-storage)
                     (lambda (&rest args)
                       (setq deleted-storage args)
                       (ert-fail "non-unsupported delete failures should not delete storage"))))
            (should-error (codex-ide-delete-session-thread "thread-delete-fail" t)
                          :type 'error)
            (should-not deleted-session)
            (should-not deleted-storage)))))))

(ert-deftest codex-ide-delete-session-thread-skip-confirmation-bypasses-prompt ()
  (let ((project-dir (codex-ide-test--make-temp-project))
        (deleted-session nil)
        (request-method nil)
        (prompted nil))
    (codex-ide-test-with-fixture project-dir
				 (codex-ide-test-with-fake-processes
				  (let ((session (codex-ide--create-process-session)))
				    (setf (codex-ide-session-thread-id session) "thread-delete-3")
				    (cl-letf (((symbol-function 'codex-ide--thread-rollout-path)
					       (lambda (_thread-id)
						 (ert-fail "thread/delete should not inspect rollout storage")))
					      ((symbol-function 'codex-ide--request-sync)
					       (lambda (_session method _params)
						 (setq request-method method)
						 '((ok . t))))
					      ((symbol-function 'yes-or-no-p)
					       (lambda (&rest _)
						 (setq prompted t)
						 (ert-fail "Unexpected confirmation prompt")))
					      ((symbol-function 'codex-ide--delete-live-thread-session)
					       (lambda (value &optional _skip-unsubscribe)
						 (setq deleted-session value)))
					      ((symbol-function 'codex-ide--delete-thread-storage)
					       (lambda (&rest _)
						 (ert-fail "thread/delete should avoid direct storage deletion"))))
				      (codex-ide-delete-session-thread "thread-delete-3" t)
				      (should (eq deleted-session session))
				      (should (equal request-method "thread/delete"))
				      (should-not prompted)))))))

(provide 'codex-ide-delete-session-thread-tests)

;;; codex-ide-delete-session-thread-tests.el ends here
